### ISSUE TITLE
下载大的文件会很快超时

### ISSUE THREAD

**Issue by linkerlin** [Leviathan1995/fari-proxy#10]
感觉超时处理上有点问题。
我下载一个100MB+的mp4视频，http协议，会在下载了几百KB后chrome提示下载失败。

**Comment by Leviathan1995** [comment]
是的  这个问题已经解决了，还没有发版，我吃完饭发一版，非常感谢

Linker Lin <notifications@github.com>于2017年11月6日 周一下午7:31写道：

**Comment by Leviathan1995** [comment]
重新发了一版
https://github.com/Leviathan1995/fari-proxy/releases/tag/v0.4.1

**Comment by Leviathan1995** [comment]
我这边测了一下 没什么问题了.非常感谢
