### ISSUE TITLE
实现看起来有点问题。。

### ISSUE THREAD

**Issue by xxxsen** [Leviathan1995/fari-proxy#17]
简单看了下代码，你每一个包都用aes和http包了下，，但实际上，，http应该只是包头混淆一下就可以了，，后面的都应该算是http的body才对。。不需要再打成http包了啊。。

**Comment by Leviathan1995** [comment]
用aes加密的不是http的body

**Comment by xxxsen** [comment]
EncodeTransfer->src.Read->s.Encode->AesEncrypt->http.NewHttp->conn.Write

嗯？ 难道不是。。整个流程应该就是上面的这些。。最终把加密的数据都塞到body里面了。。每一次的数据就是一次http消息。。但实际上不应该是这样的。。只需要发一个http包头。。剩下的都可以当成数据去塞的。。另外看了下你服务端的代码。。貌似也是把数据都包装成http请求包了。。而不是响应包。。。

**Comment by xxxsen** [comment]
最后提个建议，对异常流量可以返回各种杂七杂八的数据http响应数据，然后外层再套一层tls基本就完美了，，对外你就是一个正常的网站，而且还无法通过抓包来分析是否是协议混淆，只有你的协议才能访问到你的代理。

**Comment by Leviathan1995** [comment]
@xxxsen 你指的异常流量是指没有和我指定的http header匹配上的流量吗

**Comment by xxxsen** [comment]
解包失败，或者解包成功但是包体里面带的数据跟你要求的不符合，都可以认为是异常流量

**Comment by xxxsen** [comment]
例如你要求你的包的http header必须要有个键值对 a=123  那么当你解包成功，，但是发现并没有这个东西，，或者a的值不符合，，那都可以认为是异常的。。

**Comment by xxxsen** [comment]
主要是流量混淆的问题，如果未知流量会被限速，那你的那种肯定会被限速的，tls就不会了。
